# Generated by Django 3.2.13 on 2022-04-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=25)),
                ('first_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False, help_text='This is a staff level access')),
                ('is_active', models.BooleanField(default=True, help_text='This blocks a user at the portal.                   The user has no influence on that.')),
                ('is_activated', models.BooleanField(default=False, help_text='This is a user side activation via Phone or Email.')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
