# Generated by Django 3.2.13 on 2022-04-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220417_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='user',
            new_name='owner',
        ),
    ]
