# Generated by Django 3.2.13 on 2022-04-17 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_user_customerprofile_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='api.user'),
        ),
    ]
