# Generated by Django 3.2.13 on 2022-04-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220417_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(choices=[('p', 'Paid'), ('u', 'Unpaid')], default='u', max_length=2),
        ),
    ]
