# Generated by Django 3.2.13 on 2022-04-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_transaction_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['purchase_date']},
        ),
    ]
