# Generated by Django 3.2.13 on 2022-04-17 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_transaction_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('value', models.CharField(max_length=200, null=True)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('p', 'Paid'), ('u', 'Unpaid')], default='u', max_length=2)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['purchase_date'],
            },
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
